server.port=8080

# Redis Distributed Cluster Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# PostgreSQL Local Transaction Database Integration
spring.datasource.url=jdbc:postgresql://localhost:5432/cinema_db
spring.datasource.username=postgres
spring.datasource.password=qwerty
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# AWS SQS Infrastructure Configuration Configuration
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}
spring.cloud.aws.region.static=us-east-1

# Automatically configuration options for object mapping serializations
spring.cloud.aws.sqs.enabled=false